# Image
FROM node:18-alpine

# Déplacement de le répertoire
WORKDIR /app

# Copie et installation des dépendances
COPY package*.json ./
RUN npm install
COPY . .

# Utilisation du port 3000
EXPOSE 3000

ENV NODE_ENV=development

# Définir les droits
USER node

# Lancement de l'application
CMD ["node", "server.js"]